/* 🤖 this file was generated by svg-to-ts*/

import { MyIcon } from './svg/my-icons.model';

export type IconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];

export * from './svg/app-education.icon';
export * from './svg/app-pulse.icon';
export * from './svg/app-thumbs-up.icon';
export * from './svg/app-user.icon';
export * from './svg/my-icons.model';
