/* 🤖 this file was generated by svg-to-ts*/
export const appChat: {
  name: 'chat';
  data: string;
} = {
  name: 'chat',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M43 4H5a4 4 0 00-4 4v25a4 4 0 004 4h11l6.38 8.78a2 2 0 003.23 0L32 37h11a4 4 0 004-4V8a4 4 0 00-4-4z" fill="#f9da97"/><path d="M24 18H10a2 2 0 010-4h14a2 2 0 010 4zM39 27H10a2 2 0 010-4h29a2 2 0 010 4z" fill="#f6c253"/></svg>`
};
