/* 🤖 this file was generated by svg-to-ts*/
export const appDocument: {
  name: 'document';
  data: string;
} = {
  name: 'document',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M27.21 1H9a4 4 0 00-4 4v38a4 4 0 004 4h30a4 4 0 004-4V15z" fill="#b7e3f6"/><path d="M43 15H29a2 2 0 01-2-2V1zM33 30H15a2 2 0 010-4h18a2 2 0 010 4zM33 40H15a2 2 0 010-4h18a2 2 0 010 4z" fill="#38b1e7"/></svg>`
};
