/* 🤖 this file was generated by svg-to-ts*/
export const appUser: {
  name: 'user';
  data: string;
} = {
  name: 'user',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><path d="M24 23C12.4 23 3 29.27 3 37v7a2 2 0 002 2h38a2 2 0 002-2v-7c0-7.73-9.4-14-21-14z" fill="#4dbe86"/><path d="M24 0a13 13 0 1013 13A13 13 0 0024 0z" fill="#fac591"/><path d="M34.29 5a13 13 0 00-20.47-.1.09.09 0 00.07.14h20.4z" fill="#84523c"/></svg>`
};
