/* 🤖 this file was generated by svg-to-ts*/
export const appThumbsUp: {
  name: 'thumbs-up';
  data: string;
} = {
  name: 'thumbs-up',
  data: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><rect x="1.78" y="16" width="16" height="26" rx="2" ry="2" fill="#38b1e7"/><path d="M32.44 16.17H44a4 4 0 013.9 4.9L44.24 36.9a4 4 0 01-3.9 3.1H25a3 3 0 01-.9-.14l-6.36-2V20.55l1.38-.35a1 1 0 00.56-.45l4.61-7.92a1 1 0 00.13-.52c0-1-.11-4.43.31-5.58.49-1.36 5-3.82 7.7 1.72s0 8.51 0 8.51z" fill="#fac591"/><circle cx="11.78" cy="36" r="2" fill="#fff"/></svg>`
};
