/* 🤖 this file was generated by svg-to-ts*/

export type myIcons =
  | 'chat'
  | 'document'
  | 'education'
  | 'pulse'
  | 'thumbs-up'
  | 'user'
  | 'write';
export interface MyIcon {
  name: myIcons;
  data: string;
}
