apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
        - name: client
          image: resamsel/translatr-loadgenerator:3.3.2-0
          imagePullPolicy: "IfNotPresent"
          env:
            - name: ENDPOINT
              value: http://translatr.translatr.svc.cluster.local:9000
            - name: ACCESS_TOKEN
              value: 593bdcfe-0bc7-426b-9b80-65e930491a34
            - name: USERS
              value: "100"
            - name: MAX_RETRY_ATTEMPTS
              value: "3"
          resources:
            limits:
              cpu: 1
            requests:
              cpu: 50m
