apiVersion: apps/v1
kind: Deployment
metadata:
  name: translatr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: translatr
  template:
    metadata:
      labels:
        app: translatr
    spec:
      containers:
        - name: server
          image: resamsel/translatr:3.3.2-0
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 9000
          env:
            - name: APPLICATION_SECRET
              value: "094c8762-4689-45c7-830d-f752f82e6ac5"
            - name: BASE_URL
              value: "http://minikube.local"
            - name: ADMIN_ACCESS_TOKEN
              value: "593bdcfe-0bc7-426b-9b80-65e930491a34"
            - name: AUTH_PROVIDERS
              value: "keycloak"
            - name: DATABASE_URL
              value: "postgres://translatr:translatr@postgres-postgresql.translatr.svc.cluster.local:5432/translatr"
            - name: KEYCLOAK_HOST
              value: "sso.repanzar.com"
            - name: KEYCLOAK_CLIENT_ID
              value: "translatr-minikube"
            - name: KEYCLOAK_CLIENT_SECRET
              value: "05d9a16b-5999-49f7-b26d-996bd414c849"
            - name: LOGLEVEL_ROOT
              value: "DEBUG"
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 100m
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 15
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 1200
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: translatr
  labels:
    app: translatr
spec:
  type: NodePort
  ports:
    - port: 9000
  selector:
    app: translatr
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: translatr-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: translatr
                port:
                  number: 9000

