/* 🤖 this file was generated by svg-to-ts*/

import { MyIcon } from './svg/my-icons.model';

export type IconNameSubset<T extends Readonly<MyIcon[]>> = T[number]['name'];

export * from './svg/my-icons.model';
